# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janela_principal(object):
    def setupUi(self, janela_principal):
        janela_principal.setObjectName("janela_principal")
        janela_principal.resize(1113, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/conta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        janela_principal.setWindowIcon(icon)
        janela_principal.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(janela_principal)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1132, 806))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"/************************************************************/\n"
"/*JANELA*/\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: rgb(220, 220, 220); /* Cor do painel */\n"
"    font-size: 30px; /* Tamanho da fonte */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     background-color: rgb(220, 220, 220 ); /* Cor das abas selecionadas */\n"
"     color: black;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(190,190, 190); /* Cor das abas selecionadas */\n"
"    color: black;\n"
"}\n"
"\n"
"QHeader{\n"
"     background-color: rgb(40, 45, 50)\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:Hover {\n"
"    background-color: rgb(190, 190, 190); /* Cor das abas selecionadas */\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*CAMPOS DE TEXTO*/\n"
"\n"
"QTabWidget QLineEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 0;\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border: none;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*CAMPOS DE TEXTO*/\n"
"\n"
"QTabWidget QTextEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 0;\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px\n"
"}\n"
"\n"
"QTabWidget QTextEdit:disabled, QTextEdit:!focus {\n"
"    border: none;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*COMBOBOX*/\n"
"\n"
"QTabWidget QComboBox {\n"
"     border: 1px solid rgb(120, 120, 120);\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px\n"
"}\n"
"\n"
"QTabWidget QComboBox:disabled, QComboBox:!focus {\n"
"     border: none;\n"
"}\n"
"\n"
"QTabWidget QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QTabWidget QComboBox::drop-down {\n"
"    width: 0;\n"
"}\n"
"/************************************************************/\n"
"/*LABEL*/\n"
"QTabWidget QLabel{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"/************************************************************/\n"
"/*BUTTON*/\n"
"\n"
"QTabWidget QPushButton{\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTabWidget QPushButton:hover{\n"
"    background-color: rgb(160, 160, 160);\n"
"    border-radius: 12px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*TABLE*/\n"
"\n"
"QTabWidget QTableWidget {\n"
"    background-color: rgb(220, 220, 220); \n"
"    border: 1px solid rgb(120, 120, 120);\n"
"   \n"
"}\n"
"\n"
"/* Ajusta o canto do cabeçalho para seguir o border-radius */\n"
"QTableWidget::corner {\n"
"    border-top-left-radius: 20px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"/* Estilo dos títulos das colunas (cabeçalho horizontal) */\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* Configura o cabeçalho para não cortar as bordas superiores */\n"
"QTableWidget QHeaderView {\n"
"\n"
"    background-color: rgb(190, 190, 190);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Define a borda inferior padrão para os itens da tabela */\n"
"QTableWidget::item {\n"
"    border-bottom: none;\n"
" background-color: transparent;\n"
"}\n"
"\n"
"/* Para os itens marcados como da última linha, remove a borda inferior e deixa o fundo transparente */\n"
"QTableWidget::item[lastRow=\"true\"] {\n"
"    border-bottom: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"/************************************************************/\n"
"/*DATE*/\n"
"\n"
"QTabWidget QDateEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 12px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    padding: 7px\n"
"}\n"
"\n"
"QTabWidget QDateEdit:disabled,QTabWidget QDateEdit:!focus {\n"
"   border: none;\n"
"}\n"
"\n"
"QTabWidget QDateEdit::up-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget QDateEdit::down-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}\n"
"/************************************************************/\n"
"/*GROUPBOX*/\n"
"\n"
"QTabWidget QGroupBox{ \n"
"border-radius:7px;\n"
"border: 1px solid rgb(120,120,120);\n"
"background-color:transparent;\n"
"\n"
"}\n"
"/************************************************************/\n"
"/*CHECKBOX*/\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.campo_cliente_lancamento = QtWidgets.QComboBox(self.tab)
        self.campo_cliente_lancamento.setGeometry(QtCore.QRect(40, 48, 545, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cliente_lancamento.setFont(font)
        self.campo_cliente_lancamento.setObjectName("campo_cliente_lancamento")
        self.btn_importar_xml = QtWidgets.QPushButton(self.tab)
        self.btn_importar_xml.setGeometry(QtCore.QRect(968, 48, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_importar_xml.setFont(font)
        self.btn_importar_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_importar_xml.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/xml-_1_.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_importar_xml.setIcon(icon1)
        self.btn_importar_xml.setIconSize(QtCore.QSize(29, 29))
        self.btn_importar_xml.setFlat(False)
        self.btn_importar_xml.setObjectName("btn_importar_xml")
        self.btn_lancar_manual = QtWidgets.QPushButton(self.tab)
        self.btn_lancar_manual.setGeometry(QtCore.QRect(1024, 48, 49, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.btn_lancar_manual.setFont(font)
        self.btn_lancar_manual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_lancar_manual.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/botao-editar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_lancar_manual.setIcon(icon2)
        self.btn_lancar_manual.setIconSize(QtCore.QSize(29, 29))
        self.btn_lancar_manual.setFlat(False)
        self.btn_lancar_manual.setObjectName("btn_lancar_manual")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 136, 172, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabela_lancamentos = QtWidgets.QTableWidget(self.tab)
        self.tabela_lancamentos.setEnabled(True)
        self.tabela_lancamentos.setGeometry(QtCore.QRect(40, 168, 1033, 289))
        self.tabela_lancamentos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela_lancamentos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela_lancamentos.setRowCount(0)
        self.tabela_lancamentos.setObjectName("tabela_lancamentos")
        self.tabela_lancamentos.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(8, item)
        self.tabela_lancamentos.horizontalHeader().setDefaultSectionSize(115)
        self.tabela_lancamentos.verticalHeader().setVisible(False)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 504, 73, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(48, 104, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(150,150,150)")
        self.label_6.setObjectName("label_6")
        self.campo_cnpj_cliente = QtWidgets.QLabel(self.tab)
        self.campo_cnpj_cliente.setEnabled(False)
        self.campo_cnpj_cliente.setGeometry(QtCore.QRect(88, 104, 201, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_cliente.setFont(font)
        self.campo_cnpj_cliente.setStyleSheet("color:rgb(150,150,150)")
        self.campo_cnpj_cliente.setText("")
        self.campo_cnpj_cliente.setObjectName("campo_cnpj_cliente")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(40, 472, 172, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(40, 536, 73, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(40, 24, 172, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.total_notas_produtos = QtWidgets.QLabel(self.tab)
        self.total_notas_produtos.setGeometry(QtCore.QRect(104, 504, 241, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.total_notas_produtos.setFont(font)
        self.total_notas_produtos.setText("")
        self.total_notas_produtos.setObjectName("total_notas_produtos")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setEnabled(False)
        self.label_13.setGeometry(QtCore.QRect(328, 104, 25, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(150,150,150)")
        self.label_13.setObjectName("label_13")
        self.campo_ie = QtWidgets.QLabel(self.tab)
        self.campo_ie.setEnabled(False)
        self.campo_ie.setGeometry(QtCore.QRect(344, 104, 201, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_ie.setFont(font)
        self.campo_ie.setStyleSheet("color:rgb(150,150,150)")
        self.campo_ie.setText("")
        self.campo_ie.setObjectName("campo_ie")
        self.btn_salvar = QtWidgets.QPushButton(self.tab)
        self.btn_salvar.setGeometry(QtCore.QRect(1024, 520, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_salvar.setFont(font)
        self.btn_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/upload-de-arquivo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_salvar.setIcon(icon3)
        self.btn_salvar.setIconSize(QtCore.QSize(29, 29))
        self.btn_salvar.setFlat(False)
        self.btn_salvar.setObjectName("btn_salvar")
        self.total_notas_servico = QtWidgets.QLabel(self.tab)
        self.total_notas_servico.setGeometry(QtCore.QRect(104, 536, 241, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.total_notas_servico.setFont(font)
        self.total_notas_servico.setText("")
        self.total_notas_servico.setObjectName("total_notas_servico")
        self.campo_endereco_cliente = QtWidgets.QLabel(self.tab)
        self.campo_endereco_cliente.setEnabled(False)
        self.campo_endereco_cliente.setGeometry(QtCore.QRect(120, 152, 537, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_endereco_cliente.setFont(font)
        self.campo_endereco_cliente.setStyleSheet("color:rgb(150,150,150)")
        self.campo_endereco_cliente.setText("")
        self.campo_endereco_cliente.setObjectName("campo_endereco_cliente")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(608, 24, 113, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.data_lancamento = QtWidgets.QDateEdit(self.tab)
        self.data_lancamento.setGeometry(QtCore.QRect(608, 48, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.data_lancamento.setFont(font)
        self.data_lancamento.setObjectName("data_lancamento")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.data_consulta = QtWidgets.QDateEdit(self.tab_2)
        self.data_consulta.setGeometry(QtCore.QRect(608, 48, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.data_consulta.setFont(font)
        self.data_consulta.setObjectName("data_consulta")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 24, 172, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_importar_xml_2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_importar_xml_2.setGeometry(QtCore.QRect(1024, 48, 49, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_importar_xml_2.setFont(font)
        self.btn_importar_xml_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_importar_xml_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/pesquisa.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_importar_xml_2.setIcon(icon4)
        self.btn_importar_xml_2.setIconSize(QtCore.QSize(23, 23))
        self.btn_importar_xml_2.setObjectName("btn_importar_xml_2")
        self.campo_cliente_lancamento_2 = QtWidgets.QComboBox(self.tab_2)
        self.campo_cliente_lancamento_2.setGeometry(QtCore.QRect(40, 48, 545, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cliente_lancamento_2.setFont(font)
        self.campo_cliente_lancamento_2.setObjectName("campo_cliente_lancamento_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(608, 24, 113, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(40, 112, 193, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(40, 144, 1033, 409))
        self.tableWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(347)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabela_obrigacoes = QtWidgets.QTableWidget(self.tab_4)
        self.tabela_obrigacoes.setGeometry(QtCore.QRect(40, 128, 1033, 377))
        self.tabela_obrigacoes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabela_obrigacoes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela_obrigacoes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela_obrigacoes.setObjectName("tabela_obrigacoes")
        self.tabela_obrigacoes.setColumnCount(6)
        self.tabela_obrigacoes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_obrigacoes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_obrigacoes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_obrigacoes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_obrigacoes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_obrigacoes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_obrigacoes.setHorizontalHeaderItem(5, item)
        self.tabela_obrigacoes.horizontalHeader().setDefaultSectionSize(172)
        self.tabela_obrigacoes.verticalHeader().setVisible(False)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(40, 96, 249, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.btn_salvar_obrigacoes = QtWidgets.QPushButton(self.tab_4)
        self.btn_salvar_obrigacoes.setGeometry(QtCore.QRect(1024, 520, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_salvar_obrigacoes.setFont(font)
        self.btn_salvar_obrigacoes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar_obrigacoes.setText("")
        self.btn_salvar_obrigacoes.setIcon(icon2)
        self.btn_salvar_obrigacoes.setIconSize(QtCore.QSize(29, 29))
        self.btn_salvar_obrigacoes.setFlat(False)
        self.btn_salvar_obrigacoes.setObjectName("btn_salvar_obrigacoes")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(40, 16, 113, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.data_obrigacoes = QtWidgets.QDateEdit(self.tab_4)
        self.data_obrigacoes.setGeometry(QtCore.QRect(40, 40, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.data_obrigacoes.setFont(font)
        self.data_obrigacoes.setObjectName("data_obrigacoes")
        self.btn_consulta_lista_afazeres = QtWidgets.QPushButton(self.tab_4)
        self.btn_consulta_lista_afazeres.setGeometry(QtCore.QRect(176, 40, 49, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_consulta_lista_afazeres.setFont(font)
        self.btn_consulta_lista_afazeres.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_consulta_lista_afazeres.setText("")
        self.btn_consulta_lista_afazeres.setIcon(icon4)
        self.btn_consulta_lista_afazeres.setIconSize(QtCore.QSize(23, 23))
        self.btn_consulta_lista_afazeres.setObjectName("btn_consulta_lista_afazeres")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setGeometry(QtCore.QRect(32, 24, 481, 521))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(24, 104, 65, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.campo_nome_cliente_cadastro = QtWidgets.QLineEdit(self.groupBox)
        self.campo_nome_cliente_cadastro.setGeometry(QtCore.QRect(96, 96, 369, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.campo_nome_cliente_cadastro.setFont(font)
        self.campo_nome_cliente_cadastro.setObjectName("campo_nome_cliente_cadastro")
        self.campo_cnpj_cliente_cadastro = QtWidgets.QLineEdit(self.groupBox)
        self.campo_cnpj_cliente_cadastro.setGeometry(QtCore.QRect(96, 24, 201, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.campo_cnpj_cliente_cadastro.setFont(font)
        self.campo_cnpj_cliente_cadastro.setObjectName("campo_cnpj_cliente_cadastro")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(24, 32, 57, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(16, 168, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(220, 220, 220)")
        self.label_19.setObjectName("label_19")
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(312, 32, 25, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.campo_ie_cliente_cadastro = QtWidgets.QLineEdit(self.groupBox)
        self.campo_ie_cliente_cadastro.setGeometry(QtCore.QRect(336, 24, 129, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.campo_ie_cliente_cadastro.setFont(font)
        self.campo_ie_cliente_cadastro.setObjectName("campo_ie_cliente_cadastro")
        self.btn_salvar_cadastro = QtWidgets.QPushButton(self.groupBox)
        self.btn_salvar_cadastro.setGeometry(QtCore.QRect(416, 464, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_salvar_cadastro.setFont(font)
        self.btn_salvar_cadastro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar_cadastro.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/add-user_5089847.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_salvar_cadastro.setIcon(icon5)
        self.btn_salvar_cadastro.setIconSize(QtCore.QSize(29, 29))
        self.btn_salvar_cadastro.setFlat(False)
        self.btn_salvar_cadastro.setObjectName("btn_salvar_cadastro")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 176, 345, 49))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_folha_cadastro = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_folha_cadastro.setGeometry(QtCore.QRect(24, 16, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_folha_cadastro.setFont(font)
        self.checkBox_folha_cadastro.setObjectName("checkBox_folha_cadastro")
        self.checkBox_dctf_cadastro = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_dctf_cadastro.setGeometry(QtCore.QRect(104, 16, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_dctf_cadastro.setFont(font)
        self.checkBox_dctf_cadastro.setObjectName("checkBox_dctf_cadastro")
        self.checkBox_das_cadastro = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_das_cadastro.setGeometry(QtCore.QRect(184, 16, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_das_cadastro.setFont(font)
        self.checkBox_das_cadastro.setObjectName("checkBox_das_cadastro")
        self.checkBox_notas_cadastro = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_notas_cadastro.setGeometry(QtCore.QRect(264, 16, 65, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_notas_cadastro.setFont(font)
        self.checkBox_notas_cadastro.setObjectName("checkBox_notas_cadastro")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(16, 248, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(220, 220, 220)")
        self.label_22.setObjectName("label_22")
        self.campo_observacoes_cadastro = QtWidgets.QTextEdit(self.groupBox)
        self.campo_observacoes_cadastro.setGeometry(QtCore.QRect(24, 280, 441, 169))
        self.campo_observacoes_cadastro.setObjectName("campo_observacoes_cadastro")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(48, 16, 177, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(220, 220, 220)")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setGeometry(QtCore.QRect(568, 24, 505, 521))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(32, 32, 65, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.btn_editar_cliente = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_editar_cliente.setGeometry(QtCore.QRect(440, 464, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_editar_cliente.setFont(font)
        self.btn_editar_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editar_cliente.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/arrows_16369209.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_editar_cliente.setIcon(icon6)
        self.btn_editar_cliente.setIconSize(QtCore.QSize(29, 29))
        self.btn_editar_cliente.setFlat(False)
        self.btn_editar_cliente.setObjectName("btn_editar_cliente")
        self.campo_cnpj_cliente_editar = QtWidgets.QLineEdit(self.groupBox_2)
        self.campo_cnpj_cliente_editar.setEnabled(True)
        self.campo_cnpj_cliente_editar.setGeometry(QtCore.QRect(104, 96, 185, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.campo_cnpj_cliente_editar.setFont(font)
        self.campo_cnpj_cliente_editar.setObjectName("campo_cnpj_cliente_editar")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(24, 168, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(220, 220, 220)")
        self.label_21.setObjectName("label_21")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(32, 104, 57, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(304, 104, 25, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.campo_ie_cliente_editar = QtWidgets.QLineEdit(self.groupBox_2)
        self.campo_ie_cliente_editar.setGeometry(QtCore.QRect(328, 96, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.campo_ie_cliente_editar.setFont(font)
        self.campo_ie_cliente_editar.setObjectName("campo_ie_cliente_editar")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(24, 248, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(220, 220, 220)")
        self.label_23.setObjectName("label_23")
        self.campo_observacoes_editar = QtWidgets.QTextEdit(self.groupBox_2)
        self.campo_observacoes_editar.setGeometry(QtCore.QRect(32, 280, 457, 169))
        self.campo_observacoes_editar.setObjectName("campo_observacoes_editar")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(136, 176, 353, 49))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_folha_editar = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_folha_editar.setGeometry(QtCore.QRect(24, 16, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_folha_editar.setFont(font)
        self.checkBox_folha_editar.setObjectName("checkBox_folha_editar")
        self.checkBox_dctf_editar = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_dctf_editar.setGeometry(QtCore.QRect(112, 16, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_dctf_editar.setFont(font)
        self.checkBox_dctf_editar.setObjectName("checkBox_dctf_editar")
        self.checkBox_das_editar = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_das_editar.setGeometry(QtCore.QRect(192, 16, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_das_editar.setFont(font)
        self.checkBox_das_editar.setObjectName("checkBox_das_editar")
        self.checkBox_notas_editar = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_notas_editar.setGeometry(QtCore.QRect(272, 16, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_notas_editar.setFont(font)
        self.checkBox_notas_editar.setObjectName("checkBox_notas_editar")
        self.campo_cliente_editar = QtWidgets.QComboBox(self.groupBox_2)
        self.campo_cliente_editar.setGeometry(QtCore.QRect(104, 24, 385, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cliente_editar.setFont(font)
        self.campo_cliente_editar.setObjectName("campo_cliente_editar")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(584, 16, 137, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(220, 220, 220)")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_5, "")
        janela_principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(janela_principal)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(janela_principal)
        janela_principal.setTabOrder(self.campo_cliente_lancamento, self.data_lancamento)
        janela_principal.setTabOrder(self.data_lancamento, self.campo_cliente_lancamento_2)
        janela_principal.setTabOrder(self.campo_cliente_lancamento_2, self.data_consulta)
        janela_principal.setTabOrder(self.data_consulta, self.data_obrigacoes)
        janela_principal.setTabOrder(self.data_obrigacoes, self.campo_cnpj_cliente_cadastro)
        janela_principal.setTabOrder(self.campo_cnpj_cliente_cadastro, self.campo_ie_cliente_cadastro)
        janela_principal.setTabOrder(self.campo_ie_cliente_cadastro, self.campo_nome_cliente_cadastro)
        janela_principal.setTabOrder(self.campo_nome_cliente_cadastro, self.campo_observacoes_cadastro)
        janela_principal.setTabOrder(self.campo_observacoes_cadastro, self.campo_cliente_editar)
        janela_principal.setTabOrder(self.campo_cliente_editar, self.campo_cnpj_cliente_editar)
        janela_principal.setTabOrder(self.campo_cnpj_cliente_editar, self.campo_ie_cliente_editar)
        janela_principal.setTabOrder(self.campo_ie_cliente_editar, self.campo_observacoes_editar)
        janela_principal.setTabOrder(self.campo_observacoes_editar, self.tabela_lancamentos)
        janela_principal.setTabOrder(self.tabela_lancamentos, self.btn_lancar_manual)
        janela_principal.setTabOrder(self.btn_lancar_manual, self.btn_salvar)
        janela_principal.setTabOrder(self.btn_salvar, self.btn_salvar_cadastro)
        janela_principal.setTabOrder(self.btn_salvar_cadastro, self.btn_editar_cliente)
        janela_principal.setTabOrder(self.btn_editar_cliente, self.tableWidget_4)
        janela_principal.setTabOrder(self.tableWidget_4, self.btn_consulta_lista_afazeres)
        janela_principal.setTabOrder(self.btn_consulta_lista_afazeres, self.tabWidget)
        janela_principal.setTabOrder(self.tabWidget, self.tabela_obrigacoes)
        janela_principal.setTabOrder(self.tabela_obrigacoes, self.checkBox_folha_cadastro)
        janela_principal.setTabOrder(self.checkBox_folha_cadastro, self.checkBox_dctf_cadastro)
        janela_principal.setTabOrder(self.checkBox_dctf_cadastro, self.checkBox_das_cadastro)
        janela_principal.setTabOrder(self.checkBox_das_cadastro, self.checkBox_notas_cadastro)
        janela_principal.setTabOrder(self.btn_importar_xml_2, self.btn_salvar_obrigacoes)
        janela_principal.setTabOrder(self.btn_salvar_obrigacoes, self.checkBox_folha_editar)
        janela_principal.setTabOrder(self.checkBox_folha_editar, self.checkBox_dctf_editar)
        janela_principal.setTabOrder(self.checkBox_dctf_editar, self.checkBox_das_editar)
        janela_principal.setTabOrder(self.checkBox_das_editar, self.checkBox_notas_editar)
        janela_principal.setTabOrder(self.checkBox_notas_editar, self.btn_importar_xml)

    def retranslateUi(self, janela_principal):
        _translate = QtCore.QCoreApplication.translate
        janela_principal.setWindowTitle(_translate("janela_principal", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("janela_principal", "Consolidado"))
        self.label_2.setText(_translate("janela_principal", "Registros"))
        item = self.tabela_lancamentos.horizontalHeaderItem(0)
        item.setText(_translate("janela_principal", "CLIENTE"))
        item = self.tabela_lancamentos.horizontalHeaderItem(1)
        item.setText(_translate("janela_principal", "CNPJ"))
        item = self.tabela_lancamentos.horizontalHeaderItem(2)
        item.setText(_translate("janela_principal", "DATA"))
        item = self.tabela_lancamentos.horizontalHeaderItem(3)
        item.setText(_translate("janela_principal", "TIPO"))
        item = self.tabela_lancamentos.horizontalHeaderItem(4)
        item.setText(_translate("janela_principal", "NÚMERO NOTA"))
        item = self.tabela_lancamentos.horizontalHeaderItem(5)
        item.setText(_translate("janela_principal", "MUNICÍPIO"))
        item = self.tabela_lancamentos.horizontalHeaderItem(6)
        item.setText(_translate("janela_principal", "VALOR"))
        item = self.tabela_lancamentos.horizontalHeaderItem(7)
        item.setText(_translate("janela_principal", "RETENÇÃO"))
        item = self.tabela_lancamentos.horizontalHeaderItem(8)
        item.setText(_translate("janela_principal", "AÇÕES"))
        self.label_4.setText(_translate("janela_principal", "Produto:"))
        self.label_6.setText(_translate("janela_principal", "CNPJ:"))
        self.label_9.setText(_translate("janela_principal", "Totais"))
        self.label_12.setText(_translate("janela_principal", "Serviço:"))
        self.label_10.setText(_translate("janela_principal", "Cliente"))
        self.label_13.setText(_translate("janela_principal", "IE:"))
        self.label_16.setText(_translate("janela_principal", "Mês Referência"))
        self.data_lancamento.setDisplayFormat(_translate("janela_principal", "MM/yyyy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("janela_principal", "Lançamentos"))
        self.data_consulta.setDisplayFormat(_translate("janela_principal", "MM/yyyy"))
        self.label_7.setText(_translate("janela_principal", "Cliente"))
        self.label_8.setText(_translate("janela_principal", "Mês Referência"))
        self.label_11.setText(_translate("janela_principal", "Registros por Município"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("janela_principal", "MUNICÍPIO"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("janela_principal", "TIPO DE NOTA"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("janela_principal", "VALOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("janela_principal", "Consulta"))
        item = self.tabela_obrigacoes.horizontalHeaderItem(0)
        item.setText(_translate("janela_principal", "CLIENTE"))
        item = self.tabela_obrigacoes.horizontalHeaderItem(1)
        item.setText(_translate("janela_principal", "FOLHA"))
        item = self.tabela_obrigacoes.horizontalHeaderItem(2)
        item.setText(_translate("janela_principal", "DCTF"))
        item = self.tabela_obrigacoes.horizontalHeaderItem(3)
        item.setText(_translate("janela_principal", "DAS"))
        item = self.tabela_obrigacoes.horizontalHeaderItem(4)
        item.setText(_translate("janela_principal", "NFe"))
        item = self.tabela_obrigacoes.horizontalHeaderItem(5)
        item.setText(_translate("janela_principal", "OBSERVAÇÕES"))
        self.label_14.setText(_translate("janela_principal", "Lista de Obrigações Mensais"))
        self.label_30.setText(_translate("janela_principal", "Mês Referência"))
        self.data_obrigacoes.setDisplayFormat(_translate("janela_principal", "MM/yyyy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("janela_principal", "Obrigações"))
        self.label_17.setText(_translate("janela_principal", "Nome:"))
        self.label_18.setText(_translate("janela_principal", "CNPJ:"))
        self.label_19.setText(_translate("janela_principal", "  Obrigações:"))
        self.label_31.setText(_translate("janela_principal", "IE:"))
        self.checkBox_folha_cadastro.setText(_translate("janela_principal", "FOLHA"))
        self.checkBox_dctf_cadastro.setText(_translate("janela_principal", "DCTF"))
        self.checkBox_das_cadastro.setText(_translate("janela_principal", "DAS"))
        self.checkBox_notas_cadastro.setText(_translate("janela_principal", "NOTAS"))
        self.label_22.setText(_translate("janela_principal", "  Observações:"))
        self.label.setText(_translate("janela_principal", "  CADASTRAR CLIENTE"))
        self.label_15.setText(_translate("janela_principal", "Cliente:"))
        self.label_21.setText(_translate("janela_principal", "  Obrigações:"))
        self.label_20.setText(_translate("janela_principal", "CNPJ:"))
        self.label_32.setText(_translate("janela_principal", "IE:"))
        self.label_23.setText(_translate("janela_principal", "  Observações:"))
        self.checkBox_folha_editar.setText(_translate("janela_principal", "FOLHA"))
        self.checkBox_dctf_editar.setText(_translate("janela_principal", "DCTF"))
        self.checkBox_das_editar.setText(_translate("janela_principal", "DAS"))
        self.checkBox_notas_editar.setText(_translate("janela_principal", "NOTAS"))
        self.label_3.setText(_translate("janela_principal", "  EDITAR CLIENTE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("janela_principal", "Cadastros"))
import icons_rc


