# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janela_principal(object):
    def setupUi(self, janela_principal):
        janela_principal.setObjectName("janela_principal")
        janela_principal.resize(1126, 803)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/conta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        janela_principal.setWindowIcon(icon)
        janela_principal.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(janela_principal)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1132, 806))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"/************************************************************/\n"
"/*JANELA*/\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: rgb(220, 220, 220); /* Cor do painel */\n"
"    font-size: 30px; /* Tamanho da fonte */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     background-color: rgb(220, 220, 220 ); /* Cor das abas selecionadas */\n"
"     color: black;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(190,190, 190); /* Cor das abas selecionadas */\n"
"    color: black;\n"
"}\n"
"\n"
"QHeader{\n"
"     background-color: rgb(40, 45, 50)\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:Hover {\n"
"    background-color: rgb(190, 190, 190); /* Cor das abas selecionadas */\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*CAMPOS DE TEXTO*/\n"
"\n"
"QTabWidget QLineEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 0;\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border: none;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*CAMPOS DE TEXTO*/\n"
"\n"
"QTabWidget QTextEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 0;\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px\n"
"}\n"
"\n"
"QTabWidget QTextEdit:disabled, QTextEdit:!focus {\n"
"    border: none;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*COMBOBOX*/\n"
"\n"
"QTabWidget QComboBox {\n"
"     border: 1px solid rgb(120, 120, 120);\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px\n"
"}\n"
"\n"
"QTabWidget QComboBox:disabled, QComboBox:!focus {\n"
"     border: none;\n"
"}\n"
"\n"
"QTabWidget QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QTabWidget QComboBox::drop-down {\n"
"    width: 0;\n"
"}\n"
"/************************************************************/\n"
"/*LABEL*/\n"
"QTabWidget QLabel{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"/************************************************************/\n"
"/*BUTTON*/\n"
"\n"
"QTabWidget QPushButton{\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTabWidget QPushButton:hover{\n"
"    background-color: rgb(160, 160, 160);\n"
"    border-radius: 12px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*TABLE*/\n"
"\n"
"QTabWidget QTableWidget {\n"
"    background-color: rgb(220, 220, 220); \n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* Ajusta o cabeçalho para seguir o border-radius */\n"
"QTableWidget::corner {\n"
"    border-top-left-radius: 20px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Ajusta os títulos das colunas (cabeçalho horizontal) */\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* Impede que o cabeçalho fique cortado */\n"
"QTableWidget QHeaderView {\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"    background-color:rgb(190, 190, 190);\n"
"    font-weight: bold; \n"
"}\n"
"/************************************************************/\n"
"/*DATE*/\n"
"\n"
"QTabWidget QDateEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 12px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    padding: 7px\n"
"}\n"
"\n"
"QTabWidget QDateEdit:disabled,QTabWidget QDateEdit:!focus {\n"
"   border: none;\n"
"}\n"
"\n"
"QTabWidget QDateEdit::up-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget QDateEdit::down-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.campo_cliente_lancamento = QtWidgets.QComboBox(self.tab)
        self.campo_cliente_lancamento.setGeometry(QtCore.QRect(48, 48, 545, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cliente_lancamento.setFont(font)
        self.campo_cliente_lancamento.setObjectName("campo_cliente_lancamento")
        self.campo_cliente_lancamento.addItem("")
        self.btn_importar_xml = QtWidgets.QPushButton(self.tab)
        self.btn_importar_xml.setGeometry(QtCore.QRect(976, 48, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_importar_xml.setFont(font)
        self.btn_importar_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_importar_xml.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/filetype-xml.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_importar_xml.setIcon(icon1)
        self.btn_importar_xml.setIconSize(QtCore.QSize(25, 26))
        self.btn_importar_xml.setFlat(False)
        self.btn_importar_xml.setObjectName("btn_importar_xml")
        self.btn_lancar_manual = QtWidgets.QPushButton(self.tab)
        self.btn_lancar_manual.setGeometry(QtCore.QRect(1032, 48, 49, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.btn_lancar_manual.setFont(font)
        self.btn_lancar_manual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_lancar_manual.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pencil-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_lancar_manual.setIcon(icon2)
        self.btn_lancar_manual.setIconSize(QtCore.QSize(25, 25))
        self.btn_lancar_manual.setFlat(False)
        self.btn_lancar_manual.setObjectName("btn_lancar_manual")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(48, 184, 172, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabela_lancamentos = QtWidgets.QTableWidget(self.tab)
        self.tabela_lancamentos.setEnabled(True)
        self.tabela_lancamentos.setGeometry(QtCore.QRect(48, 216, 1033, 409))
        self.tabela_lancamentos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela_lancamentos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela_lancamentos.setRowCount(0)
        self.tabela_lancamentos.setObjectName("tabela_lancamentos")
        self.tabela_lancamentos.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lancamentos.setHorizontalHeaderItem(8, item)
        self.tabela_lancamentos.horizontalHeader().setDefaultSectionSize(114)
        self.tabela_lancamentos.verticalHeader().setVisible(False)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(48, 688, 73, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(48, 104, 25, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(150,150,150)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(48, 128, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(150,150,150)")
        self.label_6.setObjectName("label_6")
        self.campo_id = QtWidgets.QLabel(self.tab)
        self.campo_id.setEnabled(False)
        self.campo_id.setGeometry(QtCore.QRect(88, 104, 201, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_id.setFont(font)
        self.campo_id.setStyleSheet("color:rgb(150,150,150)")
        self.campo_id.setText("")
        self.campo_id.setObjectName("campo_id")
        self.campo_cnpj_cliente = QtWidgets.QLabel(self.tab)
        self.campo_cnpj_cliente.setEnabled(False)
        self.campo_cnpj_cliente.setGeometry(QtCore.QRect(88, 128, 201, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_cliente.setFont(font)
        self.campo_cnpj_cliente.setStyleSheet("color:rgb(150,150,150)")
        self.campo_cnpj_cliente.setText("")
        self.campo_cnpj_cliente.setObjectName("campo_cnpj_cliente")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(48, 656, 172, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(48, 720, 73, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(48, 24, 172, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.total_notas_produtos = QtWidgets.QLabel(self.tab)
        self.total_notas_produtos.setGeometry(QtCore.QRect(112, 688, 241, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.total_notas_produtos.setFont(font)
        self.total_notas_produtos.setText("")
        self.total_notas_produtos.setObjectName("total_notas_produtos")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setEnabled(False)
        self.label_13.setGeometry(QtCore.QRect(328, 128, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(150,150,150)")
        self.label_13.setObjectName("label_13")
        self.campo_ie = QtWidgets.QLabel(self.tab)
        self.campo_ie.setEnabled(False)
        self.campo_ie.setGeometry(QtCore.QRect(368, 128, 201, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_ie.setFont(font)
        self.campo_ie.setStyleSheet("color:rgb(150,150,150)")
        self.campo_ie.setText("")
        self.campo_ie.setObjectName("campo_ie")
        self.btn_salvar = QtWidgets.QPushButton(self.tab)
        self.btn_salvar.setGeometry(QtCore.QRect(1032, 712, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_salvar.setFont(font)
        self.btn_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_salvar.setIcon(icon3)
        self.btn_salvar.setIconSize(QtCore.QSize(25, 25))
        self.btn_salvar.setFlat(False)
        self.btn_salvar.setObjectName("btn_salvar")
        self.total_notas_servico = QtWidgets.QLabel(self.tab)
        self.total_notas_servico.setGeometry(QtCore.QRect(112, 720, 241, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.total_notas_servico.setFont(font)
        self.total_notas_servico.setText("")
        self.total_notas_servico.setObjectName("total_notas_servico")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setGeometry(QtCore.QRect(600, 56, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 32, 172, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_importar_xml_2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_importar_xml_2.setGeometry(QtCore.QRect(1024, 56, 57, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_importar_xml_2.setFont(font)
        self.btn_importar_xml_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_importar_xml_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_importar_xml_2.setIcon(icon4)
        self.btn_importar_xml_2.setIconSize(QtCore.QSize(23, 23))
        self.btn_importar_xml_2.setObjectName("btn_importar_xml_2")
        self.campo_cliente_lancamento_2 = QtWidgets.QComboBox(self.tab_2)
        self.campo_cliente_lancamento_2.setGeometry(QtCore.QRect(40, 56, 545, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cliente_lancamento_2.setFont(font)
        self.campo_cliente_lancamento_2.setObjectName("campo_cliente_lancamento_2")
        self.campo_cliente_lancamento_2.addItem("")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(600, 32, 113, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(40, 128, 193, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(40, 160, 1041, 585))
        self.tableWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(347)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(48, 16, 1009, 705))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        janela_principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(janela_principal)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(janela_principal)

    def retranslateUi(self, janela_principal):
        _translate = QtCore.QCoreApplication.translate
        janela_principal.setWindowTitle(_translate("janela_principal", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("janela_principal", "Consolidado"))
        self.campo_cliente_lancamento.setItemText(0, _translate("janela_principal", "Pan-dai"))
        self.label_2.setText(_translate("janela_principal", "Registros"))
        item = self.tabela_lancamentos.horizontalHeaderItem(0)
        item.setText(_translate("janela_principal", "CLIENTE"))
        item = self.tabela_lancamentos.horizontalHeaderItem(1)
        item.setText(_translate("janela_principal", "CNPJ"))
        item = self.tabela_lancamentos.horizontalHeaderItem(2)
        item.setText(_translate("janela_principal", "DATA"))
        item = self.tabela_lancamentos.horizontalHeaderItem(3)
        item.setText(_translate("janela_principal", "TIPO"))
        item = self.tabela_lancamentos.horizontalHeaderItem(4)
        item.setText(_translate("janela_principal", "NÚMERO NOTA"))
        item = self.tabela_lancamentos.horizontalHeaderItem(5)
        item.setText(_translate("janela_principal", "MUNICÍPIO"))
        item = self.tabela_lancamentos.horizontalHeaderItem(6)
        item.setText(_translate("janela_principal", "VALOR"))
        item = self.tabela_lancamentos.horizontalHeaderItem(7)
        item.setText(_translate("janela_principal", "RETENÇÃO"))
        item = self.tabela_lancamentos.horizontalHeaderItem(8)
        item.setText(_translate("janela_principal", "AÇÕES"))
        self.label_4.setText(_translate("janela_principal", "Produto:"))
        self.label_5.setText(_translate("janela_principal", "ID:"))
        self.label_6.setText(_translate("janela_principal", "CNPJ:"))
        self.label_9.setText(_translate("janela_principal", "Totais"))
        self.label_12.setText(_translate("janela_principal", "Serviço:"))
        self.label_10.setText(_translate("janela_principal", "Cliente"))
        self.label_13.setText(_translate("janela_principal", "IE:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("janela_principal", "Lançamentos"))
        self.dateEdit.setDisplayFormat(_translate("janela_principal", "MM/yyyy"))
        self.label_7.setText(_translate("janela_principal", "Cliente"))
        self.campo_cliente_lancamento_2.setItemText(0, _translate("janela_principal", "Pan-dai"))
        self.label_8.setText(_translate("janela_principal", "Mês Referência"))
        self.label_11.setText(_translate("janela_principal", "Registros por Município"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("janela_principal", "MUNICÍPIO"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("janela_principal", "TIPO DE NOTA"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("janela_principal", "VALOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("janela_principal", "Consulta"))
        self.groupBox.setTitle(_translate("janela_principal", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("janela_principal", "Obrigações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("janela_principal", "Cadastros"))
import icons_rc



