# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_lancar_manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janela_lancar_manual(object):
    def setupUi(self, janela_lancar_manual):
        janela_lancar_manual.setObjectName("janela_lancar_manual")
        janela_lancar_manual.resize(408, 501)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/conta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        janela_lancar_manual.setWindowIcon(icon)
        janela_lancar_manual.setStyleSheet("\n"
"/************************************************************/\n"
"/*JANELA*/\n"
"\n"
"QMainWindow::pane {\n"
"    background-color: rgb(220, 220, 220); /* Cor do painel */\n"
"    font-size: 30px; /* Tamanho da fonte */\n"
"}\n"
"\n"
"QMainWindow::tab {\n"
"     background-color: rgb(220, 220, 220 ); /* Cor das abas selecionadas */\n"
"     color: black;\n"
"}\n"
"\n"
"QMainWindow::tab:selected {\n"
"    background-color: rgb(190,190, 190); /* Cor das abas selecionadas */\n"
"    color: black;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/************************************************************/\n"
"/*CAMPOS DE TEXTO*/\n"
"\n"
"QMainWindow QLineEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 0;\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border: none;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*CAMPOS DE TEXTO*/\n"
"\n"
"QTabWidget QTextEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 0;\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px\n"
"}\n"
"\n"
"QTabWidget QTextEdit:disabled, QTextEdit:!focus {\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/************************************************************/\n"
"/*BUTTON*/\n"
"QPushButton{\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(160, 160, 160);\n"
"    border-radius: 12px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*TABLE*/\n"
"\n"
"QTabWidget QTableWidget {\n"
"    background-color: rgb(220, 220, 220); \n"
"    border: 1px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"/************************************************************/\n"
"/*DATE*/\n"
"\n"
" QDateEdit {\n"
"    border: 1px solid rgb(120, 120, 120);\n"
"    border-radius: 12px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    padding: 7px\n"
"}\n"
"\n"
" QDateEdit:disabled, QDateEdit:!focus {\n"
"   border: none;\n"
"}\n"
" QDateEdit::up-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}\n"
" QDateEdit::down-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QComboBox {\n"
"    border: none;\n"
"    background-color: rgb(190, 190, 190);\n"
"    border-radius: 12px;\n"
"    padding: 8px\n"
"}\n"
"\n"
" QComboBox:disabled, QComboBox:!focus {\n"
"    border:none;\n"
"}\n"
" QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"QComboBox::drop-down {\n"
"    width: 0;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(janela_lancar_manual)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(16, 16, 172, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.campo_cnpj_manual = QtWidgets.QLineEdit(self.centralwidget)
        self.campo_cnpj_manual.setGeometry(QtCore.QRect(16, 80, 377, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.campo_cnpj_manual.setFont(font)
        self.campo_cnpj_manual.setObjectName("campo_cnpj_manual")
        self.campo_valor_nota_manual = QtWidgets.QLineEdit(self.centralwidget)
        self.campo_valor_nota_manual.setGeometry(QtCore.QRect(16, 384, 185, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.campo_valor_nota_manual.setFont(font)
        self.campo_valor_nota_manual.setObjectName("campo_valor_nota_manual")
        self.campo_data_manual = QtWidgets.QDateEdit(self.centralwidget)
        self.campo_data_manual.setGeometry(QtCore.QRect(224, 224, 169, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.campo_data_manual.setFont(font)
        self.campo_data_manual.setObjectName("campo_data_manual")
        self.campo_numero_nota_manual = QtWidgets.QLineEdit(self.centralwidget)
        self.campo_numero_nota_manual.setGeometry(QtCore.QRect(224, 304, 169, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.campo_numero_nota_manual.setFont(font)
        self.campo_numero_nota_manual.setObjectName("campo_numero_nota_manual")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(16, 56, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:transparent")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(224, 200, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:transparent")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(16, 280, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(224, 280, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:transparent")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(16, 360, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:transparent")
        self.label_7.setObjectName("label_7")
        self.btn_importar_manual = QtWidgets.QPushButton(self.centralwidget)
        self.btn_importar_manual.setGeometry(QtCore.QRect(336, 448, 49, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_importar_manual.setFont(font)
        self.btn_importar_manual.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_importar_manual.setIcon(icon1)
        self.btn_importar_manual.setIconSize(QtCore.QSize(23, 23))
        self.btn_importar_manual.setObjectName("btn_importar_manual")
        self.campo_tipo_nota_manual = QtWidgets.QComboBox(self.centralwidget)
        self.campo_tipo_nota_manual.setGeometry(QtCore.QRect(16, 304, 185, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_tipo_nota_manual.setFont(font)
        self.campo_tipo_nota_manual.setObjectName("campo_tipo_nota_manual")
        self.campo_tipo_nota_manual.addItem("")
        self.campo_tipo_nota_manual.setItemText(0, "")
        self.campo_tipo_nota_manual.addItem("")
        self.campo_tipo_nota_manual.addItem("")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(224, 360, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:transparent")
        self.label_8.setObjectName("label_8")
        self.campo_retencao_nota_manual = QtWidgets.QComboBox(self.centralwidget)
        self.campo_retencao_nota_manual.setGeometry(QtCore.QRect(224, 384, 169, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_retencao_nota_manual.setFont(font)
        self.campo_retencao_nota_manual.setObjectName("campo_retencao_nota_manual")
        self.campo_retencao_nota_manual.addItem("")
        self.campo_retencao_nota_manual.addItem("")
        self.campo_municipio_nota_manual = QtWidgets.QLineEdit(self.centralwidget)
        self.campo_municipio_nota_manual.setGeometry(QtCore.QRect(16, 224, 185, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.campo_municipio_nota_manual.setFont(font)
        self.campo_municipio_nota_manual.setObjectName("campo_municipio_nota_manual")
        self.campo_razao_social_manual = QtWidgets.QLineEdit(self.centralwidget)
        self.campo_razao_social_manual.setGeometry(QtCore.QRect(16, 152, 377, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.campo_razao_social_manual.setFont(font)
        self.campo_razao_social_manual.setObjectName("campo_razao_social_manual")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(16, 128, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:transparent")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(16, 200, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:transparent")
        self.label_10.setObjectName("label_10")
        janela_lancar_manual.setCentralWidget(self.centralwidget)

        self.retranslateUi(janela_lancar_manual)
        QtCore.QMetaObject.connectSlotsByName(janela_lancar_manual)
        janela_lancar_manual.setTabOrder(self.campo_cnpj_manual, self.campo_razao_social_manual)
        janela_lancar_manual.setTabOrder(self.campo_razao_social_manual, self.campo_municipio_nota_manual)
        janela_lancar_manual.setTabOrder(self.campo_municipio_nota_manual, self.campo_data_manual)
        janela_lancar_manual.setTabOrder(self.campo_data_manual, self.campo_tipo_nota_manual)
        janela_lancar_manual.setTabOrder(self.campo_tipo_nota_manual, self.campo_numero_nota_manual)
        janela_lancar_manual.setTabOrder(self.campo_numero_nota_manual, self.campo_valor_nota_manual)
        janela_lancar_manual.setTabOrder(self.campo_valor_nota_manual, self.campo_retencao_nota_manual)
        janela_lancar_manual.setTabOrder(self.campo_retencao_nota_manual, self.btn_importar_manual)

    def retranslateUi(self, janela_lancar_manual):
        _translate = QtCore.QCoreApplication.translate
        janela_lancar_manual.setWindowTitle(_translate("janela_lancar_manual", "MainWindow"))
        self.label_2.setText(_translate("janela_lancar_manual", "Lançamento manual"))
        self.campo_cnpj_manual.setPlaceholderText(_translate("janela_lancar_manual", "CNPJ"))
        self.campo_valor_nota_manual.setPlaceholderText(_translate("janela_lancar_manual", "Valor"))
        self.campo_data_manual.setDisplayFormat(_translate("janela_lancar_manual", "MM/yyyy"))
        self.campo_numero_nota_manual.setPlaceholderText(_translate("janela_lancar_manual", "Número da NF"))
        self.label_3.setText(_translate("janela_lancar_manual", "CNPJ"))
        self.label_4.setText(_translate("janela_lancar_manual", "Data"))
        self.label_5.setText(_translate("janela_lancar_manual", "Tipo de Nota"))
        self.label_6.setText(_translate("janela_lancar_manual", "N° da Nota"))
        self.label_7.setText(_translate("janela_lancar_manual", "Valor"))
        self.campo_tipo_nota_manual.setItemText(1, _translate("janela_lancar_manual", "PRODUTO"))
        self.campo_tipo_nota_manual.setItemText(2, _translate("janela_lancar_manual", "SERVIÇO"))
        self.label_8.setText(_translate("janela_lancar_manual", "Retenção?"))
        self.campo_retencao_nota_manual.setItemText(0, _translate("janela_lancar_manual", "NAO"))
        self.campo_retencao_nota_manual.setItemText(1, _translate("janela_lancar_manual", "SIM"))
        self.campo_municipio_nota_manual.setPlaceholderText(_translate("janela_lancar_manual", "Município"))
        self.campo_razao_social_manual.setPlaceholderText(_translate("janela_lancar_manual", "Razão social"))
        self.label_9.setText(_translate("janela_lancar_manual", "Razão social"))
        self.label_10.setText(_translate("janela_lancar_manual", "Município"))
import icons_rc


